// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2pTBj24f1qNKjubf9CDvJbHnonesYNos',
    appId: '1:159574250803:web:48a77d4e3e04a579f11a46',
    messagingSenderId: '159574250803',
    projectId: 'forest-92045',
    authDomain: 'forest-92045.firebaseapp.com',
    storageBucket: 'forest-92045.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQd0S1RxFnWgkmf5y4a3wfjbt7IUoFAo0',
    appId: '1:159574250803:android:f5158ae38f7fc8dcf11a46',
    messagingSenderId: '159574250803',
    projectId: 'forest-92045',
    storageBucket: 'forest-92045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMZMAbKd97a3V7vOMSf2H_v71g-5OPLo',
    appId: '1:159574250803:ios:cc7e1f5531f4e5c6f11a46',
    messagingSenderId: '159574250803',
    projectId: 'forest-92045',
    storageBucket: 'forest-92045.firebasestorage.app',
    iosClientId: '159574250803-t35ritv425qjq2njtbctskcsodkv1k4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.forest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMZMAbKd97a3V7vOMSf2H_v71g-5OPLo',
    appId: '1:159574250803:ios:cc7e1f5531f4e5c6f11a46',
    messagingSenderId: '159574250803',
    projectId: 'forest-92045',
    storageBucket: 'forest-92045.firebasestorage.app',
    iosClientId: '159574250803-t35ritv425qjq2njtbctskcsodkv1k4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.forest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2pTBj24f1qNKjubf9CDvJbHnonesYNos',
    appId: '1:159574250803:web:bcd6bff26faab637f11a46',
    messagingSenderId: '159574250803',
    projectId: 'forest-92045',
    authDomain: 'forest-92045.firebaseapp.com',
    storageBucket: 'forest-92045.firebasestorage.app',
  );
}
